### ISSUE TITLE
0.0.10 - react-native dependency causes install crash

### ISSUE THREAD

**Issue by mnemotiv** [QuantumBA/tcomb-form-native-templates-material#3]
this module no longer can be used with projects which already have dependency on react-native.

eg. I'm using next major react-native version, and while running npm install on my project it rejects to finish installation.

please, explain why you introduced this change on v0.0.10 ?

because now I'm stuck on v0.0.9

**Comment by piranna** [comment]
Maybe should be set `react-native` as a `peerDependency`?

**Comment by mnemotiv** [comment]
that would be awesome :)

**Comment by adrianicv** [comment]
react-native set as `peerDependency` in 0.0.11 version. ;-)
